version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  api:
    build:
      context: ./api
    command: gunicorn --workers 3 api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data:
